name: Update Activity

on:
  schedule:
    - cron: '*/30 * * * *' # Update every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Activity
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
