name: Update Activity

on:
  schedule:
    - cron: '*/30 * * * *' # Update every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Activity
    env:
      - VERSION: v2.3.2
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@${{env.VERSION}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
